target("sandbox")
    set_kind("binary")
    add_files("*.cpp")
    add_packages("elsa", "utils", "glfw3")
    add_links("dl", "pthread", "X11", "OpenGL")
    before_build(function(target)
        target:add(find_packages("cuda"))
    end)
