includes("../utils/xmake_cpu.lua")
target("elsa")
    set_kind("static")
    add_files("**/*.cpp")
    add_deps("utils")
    add_defines("IMGUI_IMPL_OPENGL_LOADER_GLAD")
    add_packages("glfw3", "glad", "imgui_glad")
    add_links("dl", "pthread", "X11", "GL")
