includes("../utils/xmake.lua")
target("elsa")
    set_kind("static")
    add_files("./**.cpp")
    add_deps("utils")
    add_packages("glfw3", "imgui")
    add_links("dl", "pthread", "X11", "OpenGL")
    before_build(function(target)
        target:add(find_packages("cuda"))
    end)

