includes("../utils/xmake.lua")
includes("../../deps/modules/glfw/xmake.lua")
includes("../../deps/modules/imgui/xmake.lua")
target("elsa")
    set_kind("static")
    add_files("./**.cpp")
    add_deps("utils")
    add_deps("glad")
    add_deps("glfw")
    add_deps("imgui")
    before_build(function(target)
        target:add(find_packages("cuda"))
    end)

